services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_application
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: host.docker.internal
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password123
      MONGO_AUTH_SOURCE: admin
      MONGO_DB_NAME: flask_app
      MONGO_COLLECTION_NAME: users
    extra_hosts:
      - "host.docker.internal:host-gateway"